In [149]:
# Q.1
import numpy as np
import pandas as pd
Data = { 'Name' : ['Jaya','Janvi','Anjali','Priya'],
              'Age' :[19,19,20,21],
               'City':['Agra','Mathura','Delhi','Firozabad']
                 }
student_df = pd.DataFrame(Data)

In [150]:
# Q.2
student_df

     Name  Age       City
0    Jaya   19       Agra
1   Janvi   19    Mathura
2  Anjali   20      Delhi
3   Priya   21  Firozabad

In [151]:
# Q.3
student_df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [152]:
# Q.4
student_df["Name"]

0      Jaya
1     Janvi
2    Anjali
3     Priya
Name: Name, dtype: object

In [153]:
# Q.5
student_df["City"]

0         Agra
1      Mathura
2        Delhi
3    Firozabad
Name: City, dtype: object

In [154]:
# Q.6
new_df = student_df[["Name","City"]]
new_df

     Name       City
0    Jaya       Agra
1   Janvi    Mathura
2  Anjali      Delhi
3   Priya  Firozabad

In [155]:
# Q.7
Data = {
    'Book':['mulan','tom&jerry'],
    'Author': ['Robert D.San Souci','William Hanna'],
    'Price': [1600,550]
    }
book_df = pd.DataFrame(Data)
book_df

        Book              Author  Price
0      mulan  Robert D.San Souci   1600
1  tom&jerry       William Hanna    550

In [156]:
# Q.8
book_df["Piblisher"] = "Mirai pub."
book_df

        Book              Author  Price   Piblisher
0      mulan  Robert D.San Souci   1600  Mirai pub.
1  tom&jerry       William Hanna    550  Mirai pub.

In [157]:
# Q.9
Data = {'Name' : ['A','B','C','D','E']}
df = pd.DataFrame(Data)
df["SerialNo."] = np.arange(5)
df

  Name  SerialNo.
0    A          0
1    B          1
2    C          2
3    D          3
4    E          4

In [158]:
# Q.10
df = df.drop("SerialNo.",axis=1)
df

  Name
0    A
1    B
2    C
3    D
4    E

In [159]:
# Q.11
movie_df = pd.DataFrame( {
    'Movie' : ['Doraemon','Shinchan'],
    'Year' : [2002,2007],
    'Rating':[4.9,4.8],
})
movie_df

      Movie  Year  Rating
0  Doraemon  2002     4.9
1  Shinchan  2007     4.8

In [160]:
# Q.12
movie1_df = movie_df[["Movie",'Rating']]
movie1_df["Director"] = ["Hayao Miyazaki","Ai Hoshino"]
movie1_df

      Movie  Rating        Director
0  Doraemon     4.9  Hayao Miyazaki
1  Shinchan     4.8      Ai Hoshino

In [161]:
# Q.13
D = pd.Series(["Mathura","Agra"],index = [0,3])
D

0    Mathura
3       Agra
dtype: object

In [162]:
# Q.14
DF = pd.DataFrame({'Inazuma' : ['Mark','Alex','Aki','Akane']})
DF['Branch'] = D
DF

  Inazuma   Branch
0    Mark  Mathura
1    Alex      NaN
2     Aki      NaN
3   Akane     Agra

In [163]:
# Q.16
employee_df = pd.DataFrame({'Employee' : ['jay','jaya','janvi','Anjali','Priya'],
                            'Department' : ['Physics','Chemistry','Maths','English','Hindi'],
                            'Experience': [2,3,4,5,6],
                            })
new_df = employee_df[["Employee","Experience"]]
new_df

  Employee  Experience
0      jay           2
1     jaya           3
2    janvi           4
3   Anjali           5
4    Priya           6

In [164]:
# Q.17
print(employee_df["Department"])
employee_df.columns

0      Physics
1    Chemistry
2        Maths
3      English
4        Hindi
Name: Department, dtype: object

Index(['Employee', 'Department', 'Experience'], dtype='object')

In [165]:
# Q.18
employee_df["Office"] = "Head Office"
employee_df

  Employee Department  Experience       Office
0      jay    Physics           2  Head Office
1     jaya  Chemistry           3  Head Office
2    janvi      Maths           4  Head Office
3   Anjali    English           5  Head Office
4    Priya      Hindi           6  Head Office

In [166]:
# Q.19
employee_df["Office"] = np.arange(5)
employee_df

  Employee Department  Experience  Office
0      jay    Physics           2       0
1     jaya  Chemistry           3       1
2    janvi      Maths           4       2
3   Anjali    English           5       3
4    Priya      Hindi           6       4

In [167]:
# Q.20
office_names = pd.Series(["Delhi",'Mumbai','Pune'],index = [0,2,4])
employee_df["Office"] = office_names
employee_df

  Employee Department  Experience  Office
0      jay    Physics           2   Delhi
1     jaya  Chemistry           3     NaN
2    janvi      Maths           4  Mumbai
3   Anjali    English           5     NaN
4    Priya      Hindi           6    Pune

In [168]:
# Q.21
employee_df.drop('Office', axis=1, inplace=True)
print(employee_df)
print(employee_df.columns)

  Employee Department  Experience
0      jay    Physics           2
1     jaya  Chemistry           3
2    janvi      Maths           4
3   Anjali    English           5
4    Priya      Hindi           6
Index(['Employee', 'Department', 'Experience'], dtype='object')

In [169]:
# Q.22
product_df = pd.DataFrame({'Product':['A','B','C','D'],
                           'Category':[1,2,3,5],
                           'Price':[20,30,40,60]})
new_df = product_df[["Price",'Product','Category']]
new_df

   Price Product  Category
0     20       A         1
1     30       B         2
2     40       C         3
3     60       D         5

In [170]:
# Q.23
df = pd.DataFrame({'Product':['A','B','C','D'],
                           'Category':[1,2,3,5],
                           'Price':[20,30,40,60]})
new_df = df.reindex( columns = ['Category','Product','Price','Quality'])
new_df

   Category Product  Price  Quality
0         1       A     20      NaN
1         2       B     30      NaN
2         3       C     40      NaN
3         5       D     60      NaN

In [171]:
# Q.24
df = pd.DataFrame({ 'Name':['A','B','C'],
                   'Total marks':[50,40,60]})
df["Total marks"]

0    50
1    40
2    60
Name: Total marks, dtype: int64

In [172]:
# Q.26
course_df = pd.DataFrame({
    'student':['Jay','Jaya','Janvi','Anjali','Priya'],
    'Course':['B.Tech','B.Tech','B.Tech','B.Tech','B.Tech'],
    'Score':[10,20,30,40,50]
})
print(course_df.columns)
print(course_df["student"])
df = course_df[["student",'Score']]
print(df)
df["Batch"] = 2026
print(df)

Index(['student', 'Course', 'Score'], dtype='object')
0       Jay
1      Jaya
2     Janvi
3    Anjali
4     Priya
Name: student, dtype: object
  student  Score
0     Jay     10
1    Jaya     20
2   Janvi     30
3  Anjali     40
4   Priya     50
  student  Score  Batch
0     Jay     10   2026
1    Jaya     20   2026
2   Janvi     30   2026
3  Anjali     40   2026
4   Priya     50   2026

In [173]:
# Q.27
Travel_df = pd.DataFrame({
    'Name':['a','b','c','d','e']
})
print(Travel_df)
Travel_df["code"] = np.arange(5)
print(Travel_df)
S = pd.Series([100,200],index = [1,4])
Travel_df["code"] = S
print(Travel_df)

  Name
0    a
1    b
2    c
3    d
4    e
  Name  code
0    a     0
1    b     1
2    c     2
3    d     3
4    e     4
  Name   code
0    a    NaN
1    b  100.0
2    c    NaN
3    d    NaN
4    e  200.0

In [174]:
# Q.28
School_df = pd.DataFrame({
    'Student':['Priya','Anshika'],
    'Class':[431,326],
    'Section':['FF','AL']
})
df = School_df.reindex(columns = ['Student','Class','Section','House'])
df["House"] = "Mathura"
print(School_df)
print(df)

   Student  Class Section
0    Priya    431      FF
1  Anshika    326      AL
   Student  Class Section    House
0    Priya    431      FF  Mathura
1  Anshika    326      AL  Mathura

In [175]:
# Q.29
inventory_df = pd.DataFrame({
    "Item":['pen','rubber','Scale','bag'],
    "Quantity": [2,2,1,1],
    "Price": [10,5,20,150]
})
discount = pd.Series([10, 20], index=[0, 2])
inventory_df["Discount"] = discount
print("After adding Discount column:")
print(inventory_df)
del inventory_df["Discount"]
print("After deleting Discount column:")
print(inventory_df)

After adding Discount column:
     Item  Quantity  Price  Discount
0     pen         2     10      10.0
1  rubber         2      5       NaN
2   Scale         1     20      20.0
3     bag         1    150       NaN
After deleting Discount column:
     Item  Quantity  Price
0     pen         2     10
1  rubber         2      5
2   Scale         1     20
3     bag         1    150

In [176]:
# Q.30
lab_df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Karan", "Neha"],
    "Age": [20, 21, 19, 22],
    "Course Name": ["CSE", "IT", "CSE", "AI"],
    "Marks": [85, 90, 78, 88]
})
print(lab_df)
print(lab_df.columns)
print(lab_df["Name"])
print(lab_df["Course Name"])
small_df = lab_df[["Name", "Marks"]]
print(small_df)
lab_df["Result"] = ["Pass", "Pass", "Pass", "Pass"]
print(lab_df)
del lab_df["Result"]
print(lab_df)

    Name  Age Course Name  Marks
0   Aman   20         CSE     85
1   Riya   21          IT     90
2  Karan   19         CSE     78
3   Neha   22          AI     88
Index(['Name', 'Age', 'Course Name', 'Marks'], dtype='object')
0     Aman
1     Riya
2    Karan
3     Neha
Name: Name, dtype: object
0    CSE
1     IT
2    CSE
3     AI
Name: Course Name, dtype: object
    Name  Marks
0   Aman     85
1   Riya     90
2  Karan     78
3   Neha     88
    Name  Age Course Name  Marks Result
0   Aman   20         CSE     85   Pass
1   Riya   21          IT     90   Pass
2  Karan   19         CSE     78   Pass
3   Neha   22          AI     88   Pass
    Name  Age Course Name  Marks
0   Aman   20         CSE     85
1   Riya   21          IT     90
2  Karan   19         CSE     78
3   Neha   22          AI     88